### ISSUE TITLE
自定义卡片视图列数

### ISSUE THREAD

**Issue by SaXz2** [sethyuan/orca-note#36]
使用场景：全屏后想要一列三个的大卡片显示
添加位置参考：

![Image](https://github.com/user-attachments/assets/84cb66f5-0055-4cb4-a6d8-2fd173c04d88)

**Comment by SaXz2** [comment]
使用自定义一行卡片数的朋友可以先在custom.css中添加以下CSS来解决卡片变大的问题：


```css
.orca-query-cards>.orca-block {
  content-visibility: visible;
  overflow: clip;
}
```
