### ISSUE TITLE
希望能改字体

### ISSUE THREAD

**Issue by kathleensun** [sethyuan/orca-note#8]
好希望能改字体，外观好看对笔记很重要啊~~啊~~

**Comment by sethyuan** [comment]
可以改的，虎鲸笔记允许用户通过`custom.css`文件自定义样式，包括字体。`custom.css`文件在用户文档文件夹下的orca文件夹中：
![image](https://github.com/user-attachments/assets/ba0ed4e8-fb05-4eac-ba9b-ae71f77a36da)

虎鲸笔记中有几个字体变量，其中`--orca-fontfamily-editor`是编辑器字体，`--orca-fontfamily-ui`是用户界面字体。参考如下：

```css
:root {
  --orca-fontfamily-editor: "想要使用的字体名称", var(--orca-fontfamily-fallback);
}
```
